// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "Version",
    "tagline": "Rapporter les choses compliquées et les mener à bien.",
    "story": "Un petit Shiba IA qui vit dans votre ordinateur et rassemble vos fichiers, tâches et idées dispersés.",
    "checkForUpdates": "Rechercher des mises à jour",
    "releaseNotes": "Notes de version",
    "reportIssue": "Signaler un problème",
    "website": "Site web",
    "github": "GitHub",
    "wechatGroupTitle": "Scannez pour rejoindre le groupe WeChat"
  }
};

export default about;
