// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Sélectionner le modèle",
    "engineHeader": "{{name}} Engine",
    "addModel": "Ajouter un modèle",

    "openCliSettings": "Gestion des moteurs",
    "switchChannel": "Changer de canal",
    "selectChannel": "Sélectionner un canal",
    "refreshConfig": "Actualiser la configuration",
    "refreshingConfig": "Actualisation...",
    "reloadConfig": "Recharger la configuration",
    "reloadingConfig": "Rechargement de la configuration...",
    "discoverModels": "Découvrir les modèles depuis le CLI",
    "discoveringModels": "Découverte des modèles...",
    "emptyChannelModelsTitle": "Ce fournisseur n'a pas encore de modèle",
    "emptyChannelModelsHint": "Cliquez sur « Ajouter un modèle » ci-dessous pour ajouter un modèle personnalisé",
    "refreshConfigFailed": "Échec de l'actualisation : {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "Dernier modèle de codage agentique de pointe."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modèle de codage agentique équilibré pour le travail quotidien."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modèle de codage agentique rapide et abordable."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modèle de pointe pour le codage complexe, la recherche et le travail concret."
      }
    }
  }
};

export default models;
