// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "版本",
    "tagline": "把複雜的事，叼回來做好。",
    "story": "一隻住在電腦裡的 AI 小柴犬，把散落的檔案、任務和靈感一件件叼回來。",
    "checkForUpdates": "檢查更新",
    "releaseNotes": "版本說明",
    "reportIssue": "回報問題",
    "website": "官方網站",
    "github": "GitHub"
  }
};

export default about;
