// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
const providers = {
  "providers": {
    "localConfig": "本地配置",
    "claude": {
      "label": "Claude"
    },
    "codex": {
      "label": "Codex"
    },
    "gemini": {
      "label": "Gemini"
    },
    "kimi": {
      "label": "Kimi"
    },
    "grok": {
      "label": "Grok"
    },
    "opencode": {
      "label": "OpenCode"
    }
  }
};

export default providers;
