// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "Versão",
    "tagline": "Busque o que é complicado e faça acontecer.",
    "story": "Um pequeno Shiba de IA que vive no seu computador e reúne arquivos, tarefas e ideias espalhadas.",
    "checkForUpdates": "Verificar atualizações",
    "releaseNotes": "Notas de versão",
    "reportIssue": "Relatar problema",
    "website": "Site",
    "github": "GitHub",
    "wechatGroupTitle": "Escaneie para entrar no grupo do WeChat"
  }
};

export default about;
