// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Selecionar modelo",
    "subscribeToUse": "Assine para usar",
    "engineHeader": "{{name}} Engine",
    "addModel": "Adicionar modelo",

    "openCliSettings": "Gerenciamento de mecanismos",
    "switchChannel": "Trocar canal",
    "selectChannel": "Selecionar canal",
    "refreshConfig": "Atualizar configuração",
    "refreshingConfig": "Atualizando...",
    "reloadConfig": "Recarregar configuração",
    "reloadingConfig": "Recarregando configuração...",
    "discoverModels": "Descobrir modelos pela CLI",
    "discoveringModels": "Descobrindo modelos...",
    "emptyChannelModelsTitle": "Este provedor ainda não tem modelos",
    "emptyChannelModelsHint": "Clique em «Adicionar modelo» abaixo para adicionar um modelo personalizado",
    "refreshConfigFailed": "Falha ao atualizar: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "Modelo de programação agêntica de fronteira mais recente."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modelo de programação agêntica equilibrado para o dia a dia."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modelo de programação agêntica rápido e acessível."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modelo de fronteira para programação complexa, pesquisa e trabalho do mundo real."
      }
    }
  }
};

export default models;
