// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "バージョン",
    "tagline": "複雑なことを、くわえて持ち帰り、やり遂げる。",
    "story": "パソコンに住む小さな AI 柴犬が、散らばったファイル、タスク、アイデアをひとつに集めます。",
    "checkForUpdates": "アップデートを確認",
    "releaseNotes": "リリースノート",
    "reportIssue": "問題を報告",
    "website": "ウェブサイト",
    "github": "GitHub",
    "wechatGroupTitle": "スキャンして WeChat グループに参加"
  }
};

export default about;
