// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "モデルを選択",
    "subscribeToUse": "購読して使用",
    "engineHeader": "{{name}} エンジン",
    "addModel": "モデルを追加",

    "openCliSettings": "エンジン管理",
    "switchChannel": "チャネルを切り替え",
    "selectChannel": "チャネルを選択",
    "refreshConfig": "設定を更新",
    "refreshingConfig": "更新中...",
    "reloadConfig": "設定を再読み込み",
    "reloadingConfig": "設定を再読み込み中...",
    "discoverModels": "CLI からモデルを検出",
    "discoveringModels": "モデルを検出中...",
    "emptyChannelModelsTitle": "このプロバイダーにはまだモデルがありません",
    "emptyChannelModelsHint": "下の「モデルを追加」をクリックして、カスタムモデルを追加してください",
    "refreshConfigFailed": "更新に失敗しました: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "最新のフロンティアエージェント型コーディングモデル。"
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "日常業務向けのバランス型エージェントコーディングモデル。"
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "高速で手頃なエージェント型コーディングモデル。"
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "複雑なコーディング、研究、実務向けのフロンティアモデル。"
      }
    }
  }
};

export default models;
