// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "Versión",
    "tagline": "Trae de vuelta lo complicado y hazlo realidad.",
    "story": "Un pequeño Shiba de IA que vive en tu ordenador y reúne archivos, tareas e ideas dispersas.",
    "checkForUpdates": "Buscar actualizaciones",
    "releaseNotes": "Notas de la versión",
    "reportIssue": "Informar de un problema",
    "website": "Sitio web",
    "github": "GitHub",
    "wechatGroupTitle": "Escanea para unirte al grupo de WeChat"
  }
};

export default about;
