// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Seleccionar modelo",
    "engineHeader": "{{name}} Engine",
    "addModel": "Añadir modelo",

    "openCliSettings": "Gestión de motores",
    "switchChannel": "Cambiar canal",
    "selectChannel": "Seleccionar canal",
    "refreshConfig": "Actualizar configuración",
    "refreshingConfig": "Actualizando...",
    "reloadConfig": "Recargar configuración",
    "reloadingConfig": "Recargando configuración...",
    "discoverModels": "Descubrir modelos desde CLI",
    "discoveringModels": "Descubriendo modelos...",
    "emptyChannelModelsTitle": "Este proveedor aún no tiene modelos",
    "emptyChannelModelsHint": "Haga clic en «Añadir modelo» a continuación para agregar un modelo personalizado",
    "refreshConfigFailed": "Error al actualizar: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "El modelo de codificación agéntica de frontera más reciente."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modelo de codificación agéntica equilibrado para el trabajo diario."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modelo de codificación agéntica rápido y asequible."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modelo de frontera para codificación compleja, investigación y trabajo del mundo real."
      }
    }
  }
};

export default models;
