// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "संस्करण",
    "tagline": "मुश्किल काम वापस लाओ—और पूरा करके दिखाओ।",
    "story": "आपके कंप्यूटर में रहने वाला छोटा AI शिबा बिखरी फ़ाइलें, काम और विचार एक जगह लाता है।",
    "checkForUpdates": "अपडेट जांचें",
    "releaseNotes": "रिलीज़ नोट्स",
    "reportIssue": "समस्या रिपोर्ट करें",
    "website": "वेबसाइट",
    "github": "GitHub",
    "wechatGroupTitle": "WeChat ग्रुप में शामिल होने के लिए स्कैन करें"
  }
};

export default about;
