// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "मॉडल चुनें",
    "engineHeader": "{{name}} Engine",
    "addModel": "मॉडल जोड़ें",

    "openCliSettings": "इंजन प्रबंधन",
    "switchChannel": "चैनल बदलें",
    "selectChannel": "चैनल चुनें",
    "refreshConfig": "कॉन्फ़िग रीफ़्रेश करें",
    "refreshingConfig": "रीफ़्रेश हो रहा है...",
    "reloadConfig": "कॉन्फ़िग फिर से लोड करें",
    "reloadingConfig": "कॉन्फ़िग फिर से लोड हो रहा है...",
    "discoverModels": "CLI से मॉडल खोजें",
    "discoveringModels": "मॉडल खोजे जा रहे हैं...",
    "emptyChannelModelsTitle": "इस प्रदाता के पास अभी कोई मॉडल नहीं है",
    "emptyChannelModelsHint": "नीचे «मॉडल जोड़ें» पर क्लिक करके कस्टम मॉडल जोड़ें",
    "refreshConfigFailed": "रीफ़्रेश विफल: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "नवीनतम फ्रंटियर एजेंटिक कोडिंग मॉडल।"
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "रोज़मर्रा के काम के लिए संतुलित एजेंटिक कोडिंग मॉडल।"
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "तेज़ और किफ़ायती एजेंटिक कोडिंग मॉडल।"
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "जटिल कोडिंग, अनुसंधान और वास्तविक कार्य के लिए फ्रंटियर मॉडल।"
      }
    }
  }
};

export default models;
