// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Выбрать модель",
    "engineHeader": "{{name}} Engine",
    "addModel": "Добавить модель",

    "openCliSettings": "Управление движками",
    "switchChannel": "Сменить канал",
    "selectChannel": "Выбрать канал",
    "refreshConfig": "Обновить конфигурацию",
    "refreshingConfig": "Обновление...",
    "reloadConfig": "Перезагрузить конфигурацию",
    "reloadingConfig": "Перезагрузка конфигурации...",
    "discoverModels": "Найти модели через CLI",
    "discoveringModels": "Поиск моделей...",
    "emptyChannelModelsTitle": "У этого провайдера пока нет моделей",
    "emptyChannelModelsHint": "Нажмите «Добавить модель» ниже, чтобы добавить пользовательскую модель",
    "refreshConfigFailed": "Не удалось обновить: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "Новейшая передовая агентная модель для программирования."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Сбалансированная агентная модель для программирования в повседневной работе."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Быстрая и доступная агентная модель для программирования."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Передовая модель для сложного программирования, исследований и реальных задач."
      }
    }
  }
};

export default models;
