// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "모델 선택",
    "subscribeToUse": "구독 후 사용",
    "engineHeader": "{{name}} 엔진",
    "addModel": "모델 추가",

    "openCliSettings": "엔진 관리",
    "switchChannel": "채널 전환",
    "selectChannel": "채널 선택",
    "refreshConfig": "설정 새로고침",
    "refreshingConfig": "새로고침 중...",
    "reloadConfig": "설정 다시 불러오기",
    "reloadingConfig": "설정 다시 불러오는 중...",
    "discoverModels": "CLI에서 모델 검색",
    "discoveringModels": "모델 검색 중...",
    "emptyChannelModelsTitle": "이 공급자에는 아직 모델이 없습니다",
    "emptyChannelModelsHint": "아래의 「모델 추가」를 클릭하여 사용자 지정 모델을 추가하세요",
    "refreshConfigFailed": "새로고침 실패: {{message}}",
        "claude": {
      "fable5": {
        "label": "Fable 5",
        "description": "Fable 5 · Most powerful · Mythos-class"
      },
      "opus5": {
        "label": "Opus 5",
        "description": "Opus 5 · Latest Opus upgrade"
      },
      "opus48": {
        "label": "Opus 4.8",
        "description": "Opus 4.8 · Previous Opus generation"
      },
      "sonnet5": {
        "label": "Sonnet 5",
        "description": "Sonnet 5 · Upgraded Sonnet model"
      },
      "sonnet47": {
        "label": "Sonnet 4.7",
        "description": "Sonnet 4.7 · Default recommended model"
      },
      "sonnet46": {
        "label": "Sonnet 4.6",
        "description": "Sonnet 4.6 · Default recommended model"
      },
      "haiku45": {
        "label": "Haiku 4.5",
        "description": "Haiku · Fastest for quick answers"
      }
    },
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "최신 프론티어 에이전트 코딩 모델."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "일상 작업을 위한 균형 잡힌 에이전트 코딩 모델."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "빠르고 경제적인 에이전트 코딩 모델."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "복잡한 코딩, 연구, 실무 작업을 위한 프론티어 모델."
      }
    }
  }
};

export default models;
